/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_03;

/**
 *
 * @author Nguyễn Trần Quang Khải_ 2280601376_ 22DTHG3
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuTaoNhanVien = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuLietKeTatCa = new javax.swing.JMenuItem();
        mnuLietKeTheoNgach = new javax.swing.JMenuItem();
        mnuLietKeTheoPhongBan = new javax.swing.JMenuItem();
        mnuLietKeTheoLoaiHD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuTinhLuongTatCa = new javax.swing.JMenuItem();
        mnuTinhLuongTheoNgach = new javax.swing.JMenuItem();
        mnuTinhLuongTheoPhongBan = new javax.swing.JMenuItem();
        mnuTinhLuongTheoLoaiHD = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Quản lý");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuTaoNhanVien.setText("Tạo nhân viên");
        mnuTaoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTaoNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTaoNhanVien);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Liệt kê");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mnuLietKeTatCa.setText("Tất cả");
        mnuLietKeTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLietKeTatCaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLietKeTatCa);

        mnuLietKeTheoNgach.setText("Theo ngạch");
        mnuLietKeTheoNgach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLietKeTheoNgachActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLietKeTheoNgach);

        mnuLietKeTheoPhongBan.setText("Theo phòng ban");
        mnuLietKeTheoPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLietKeTheoPhongBanActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLietKeTheoPhongBan);

        mnuLietKeTheoLoaiHD.setText("Theo loại hợp đồng");
        mnuLietKeTheoLoaiHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLietKeTheoLoaiHDActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLietKeTheoLoaiHD);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tính lương");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        mnuTinhLuongTatCa.setText("Tất cả");
        mnuTinhLuongTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTinhLuongTatCaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuTinhLuongTatCa);

        mnuTinhLuongTheoNgach.setText("Theo ngạch");
        mnuTinhLuongTheoNgach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTinhLuongTheoNgachActionPerformed(evt);
            }
        });
        jMenu3.add(mnuTinhLuongTheoNgach);

        mnuTinhLuongTheoPhongBan.setText("Theo phòng ban");
        mnuTinhLuongTheoPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTinhLuongTheoPhongBanActionPerformed(evt);
            }
        });
        jMenu3.add(mnuTinhLuongTheoPhongBan);

        mnuTinhLuongTheoLoaiHD.setText("Theo loại hợp đồng");
        mnuTinhLuongTheoLoaiHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTinhLuongTheoLoaiHDActionPerformed(evt);
            }
        });
        jMenu3.add(mnuTinhLuongTheoLoaiHD);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Hệ thống");

        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        jMenu4.add(mnuThoat);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void mnuTaoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTaoNhanVienActionPerformed
        frmTaoNhanVien form = new frmTaoNhanVien();
        form.setVisible(true);
    }//GEN-LAST:event_mnuTaoNhanVienActionPerformed

    private void mnuLietKeTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLietKeTatCaActionPerformed
        frmTimKiemNhanVien form = new frmTimKiemNhanVien();
        form.hienThiTatCa();
        form.setVisible(true);
    }//GEN-LAST:event_mnuLietKeTatCaActionPerformed

    private void mnuLietKeTheoNgachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLietKeTheoNgachActionPerformed
        frmTimKiemNhanVien form = new frmTimKiemNhanVien();
        form.setVisible(true);
        form.setCheDoLietKe("NGACH");
    }//GEN-LAST:event_mnuLietKeTheoNgachActionPerformed

    private void mnuLietKeTheoPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLietKeTheoPhongBanActionPerformed
        frmTimKiemNhanVien form = new frmTimKiemNhanVien();
        form.setVisible(true);
        form.setCheDoLietKe("PHONGBAN");
    }//GEN-LAST:event_mnuLietKeTheoPhongBanActionPerformed

    private void mnuLietKeTheoLoaiHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLietKeTheoLoaiHDActionPerformed
        frmTimKiemNhanVien form = new frmTimKiemNhanVien();
        form.setVisible(true);
        form.setCheDoLietKe("LOAIHD");
    }//GEN-LAST:event_mnuLietKeTheoLoaiHDActionPerformed

    private void mnuTinhLuongTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTinhLuongTatCaActionPerformed
        frmTinhLuong form = new frmTinhLuong();
        form.tinhLuongTatCa();
        form.setVisible(true);
    }//GEN-LAST:event_mnuTinhLuongTatCaActionPerformed

    private void mnuTinhLuongTheoNgachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTinhLuongTheoNgachActionPerformed
        frmTinhLuong form = new frmTinhLuong();
        form.setVisible(true);
        form.setCheDoTinhLuong("NGACH");
    }//GEN-LAST:event_mnuTinhLuongTheoNgachActionPerformed

    private void mnuTinhLuongTheoPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTinhLuongTheoPhongBanActionPerformed
        frmTinhLuong form = new frmTinhLuong();
        form.setVisible(true);
        form.setCheDoTinhLuong("PHONGBAN");
    }//GEN-LAST:event_mnuTinhLuongTheoPhongBanActionPerformed

    private void mnuTinhLuongTheoLoaiHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTinhLuongTheoLoaiHDActionPerformed
        frmTinhLuong form = new frmTinhLuong();
        form.setVisible(true);
        form.setCheDoTinhLuong("LOAIHD");
    }//GEN-LAST:event_mnuTinhLuongTheoLoaiHDActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuLietKeTheoLoaiHD;
    private javax.swing.JMenuItem mnuLietKeTheoNgach;
    private javax.swing.JMenuItem mnuLietKeTheoPhongBan;
    private javax.swing.JMenuItem mnuLietKeTatCa;
    private javax.swing.JMenuItem mnuTaoNhanVien;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JMenuItem mnuTinhLuongTheoLoaiHD;
    private javax.swing.JMenuItem mnuTinhLuongTheoNgach;
    private javax.swing.JMenuItem mnuTinhLuongTheoPhongBan;
    private javax.swing.JMenuItem mnuTinhLuongTatCa;
    // End of variables declaration//GEN-END:variables
}


