/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_03;

import javax.swing.JOptionPane;

/**
 *
 * @author Nguyễn Trần Quang Khải_ 2280601376_ 22DTHG3
 */
public class frmTaoNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form frmTaoNhanVien
     */
    public frmTaoNhanVien() {
        initComponents();
        // Ẩn panel NVHD ban đầu
        pnlNVHD.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLoaiNV = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtPhongBan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbNVBC = new javax.swing.JRadioButton();
        rbNVHD = new javax.swing.JRadioButton();
        pnlNVBC = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHeSoLuong = new javax.swing.JTextField();
        txtSoNamCongTac = new javax.swing.JTextField();
        pnlNVHD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLuongHopDong = new javax.swing.JTextField();
        cbLoaiHopDong = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        buttonGroupLoaiNV.add(rbNVBC);
        buttonGroupLoaiNV.add(rbNVHD);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tạo nhân viên");

        jLabel1.setText("Họ tên:");

        jLabel2.setText("Phòng ban:");

        jLabel3.setText("Loại nhân viên:");

        rbNVBC.setSelected(true);
        rbNVBC.setText("Nhân viên biên chế");
        rbNVBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNVBCActionPerformed(evt);
            }
        });

        rbNVHD.setText("Nhân viên hợp đồng");
        rbNVHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNVHDActionPerformed(evt);
            }
        });

        pnlNVBC.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin NVBC"));

        jLabel4.setText("Hệ số lương:");

        jLabel5.setText("Số năm công tác:");

        javax.swing.GroupLayout pnlNVBCLayout = new javax.swing.GroupLayout(pnlNVBC);
        pnlNVBC.setLayout(pnlNVBCLayout);
        pnlNVBCLayout.setHorizontalGroup(
            pnlNVBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNVBCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNVBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlNVBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtSoNamCongTac))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNVBCLayout.setVerticalGroup(
            pnlNVBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNVBCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNVBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNVBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoNamCongTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNVHD.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin NVHD"));

        jLabel6.setText("Lương hợp đồng:");

        jLabel7.setText("Loại hợp đồng:");

        cbLoaiHopDong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NH", "DH" }));

        javax.swing.GroupLayout pnlNVHDLayout = new javax.swing.GroupLayout(pnlNVHD);
        pnlNVHD.setLayout(pnlNVHDLayout);
        pnlNVHDLayout.setHorizontalGroup(
            pnlNVHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNVHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNVHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlNVHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLuongHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(cbLoaiHopDong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNVHDLayout.setVerticalGroup(
            pnlNVHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNVHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNVHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLuongHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNVHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbLoaiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(rbNVBC)
                        .addGap(18, 18, 18)
                        .addComponent(rbNVHD))
                    .addComponent(pnlNVBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNVHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnDong)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbNVBC)
                    .addComponent(rbNVHD))
                .addGap(18, 18, 18)
                .addComponent(pnlNVBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlNVHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnDong))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNVBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNVBCActionPerformed
        pnlNVBC.setVisible(true);
        pnlNVHD.setVisible(false);
    }//GEN-LAST:event_rbNVBCActionPerformed

    private void rbNVHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNVHDActionPerformed
        pnlNVBC.setVisible(false);
        pnlNVHD.setVisible(true);
    }//GEN-LAST:event_rbNVHDActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            String hoTen = txtHoTen.getText().trim();
            String phongBan = txtPhongBan.getText().trim();
            
            if (hoTen.isEmpty() || phongBan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            NhanVien nv = null;
            
            if (rbNVBC.isSelected()) {
                // Tạo NVBC
                String heSoStr = txtHeSoLuong.getText().trim();
                String soNamStr = txtSoNamCongTac.getText().trim();
                
                if (heSoStr.isEmpty() || soNamStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin NVBC!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                double heSoLuong = Double.parseDouble(heSoStr);
                int soNamCongTac = Integer.parseInt(soNamStr);
                
                if (heSoLuong <= 0 || soNamCongTac < 0) {
                    JOptionPane.showMessageDialog(this, "Hệ số lương phải > 0 và số năm công tác >= 0!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                nv = new NVBC(hoTen, phongBan, heSoLuong, soNamCongTac);
            } else {
                // Tạo NVHD
                String luongStr = txtLuongHopDong.getText().trim();
                
                if (luongStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập lương hợp đồng!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                double luongHopDong = Double.parseDouble(luongStr);
                String loaiHD = (String) cbLoaiHopDong.getSelectedItem();
                
                if (luongHopDong <= 0) {
                    JOptionPane.showMessageDialog(this, "Lương hợp đồng phải > 0!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                nv = new NVHD(hoTen, phongBan, luongHopDong, loaiHD);
            }
            
            // Thêm vào danh sách
            QLNhanVien.quanLy.themNhanVien(nv);
            
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            
            // Xóa form
            txtHoTen.setText("");
            txtPhongBan.setText("");
            txtHeSoLuong.setText("");
            txtSoNamCongTac.setText("");
            txtLuongHopDong.setText("");
            cbLoaiHopDong.setSelectedIndex(0);
            rbNVBC.setSelected(true);
            pnlNVBC.setVisible(true);
            pnlNVHD.setVisible(false);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu số không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTaoNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLuu;
    private javax.swing.ButtonGroup buttonGroupLoaiNV;
    private javax.swing.JComboBox<String> cbLoaiHopDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnlNVBC;
    private javax.swing.JPanel pnlNVHD;
    private javax.swing.JRadioButton rbNVBC;
    private javax.swing.JRadioButton rbNVHD;
    private javax.swing.JTextField txtHeSoLuong;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuongHopDong;
    private javax.swing.JTextField txtPhongBan;
    private javax.swing.JTextField txtSoNamCongTac;
    // End of variables declaration//GEN-END:variables
}


