/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_03;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
/**
 *
 * @author Nguyễn Trần Quang Khải_ 2280601376_ 22DTHG3
 */
public class frmTinhLuong extends javax.swing.JFrame {
    
    private String cheDoTinhLuong = ""; // "NGACH", "PHONGBAN", "LOAIHD"
    private DecimalFormat df = new DecimalFormat("#,###.00");

    /**
     * Creates new form frmTinhLuong
     */
    public frmTinhLuong() {
        initComponents();
    }
    
    public void setCheDoTinhLuong(String cheDo) {
        this.cheDoTinhLuong = cheDo;
        if ("NGACH".equals(cheDo)) {
            lblTieuDe.setText("Tính lương theo ngạch");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(true);
            txtPhongBan.setVisible(false);
            cbLoaiHD.setVisible(false);
        } else if ("PHONGBAN".equals(cheDo)) {
            lblTieuDe.setText("Tính lương theo phòng ban");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(false);
            txtPhongBan.setVisible(true);
            cbLoaiHD.setVisible(false);
        } else if ("LOAIHD".equals(cheDo)) {
            lblTieuDe.setText("Tính lương theo loại hợp đồng");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(false);
            txtPhongBan.setVisible(false);
            cbLoaiHD.setVisible(true);
        }
    }
    
    public void tinhLuongTatCa() {
        double tongLuong = QLNhanVien.quanLy.tinhTongLuong();
        txtTongLuong.setText(df.format(tongLuong));
        lblTieuDe.setText("Tính lương tất cả nhân viên");
        pnlTimKiem.setVisible(false);
        
        // Hiển thị danh sách
        Vector<Vector<String>> data = QLNhanVien.quanLy.hienThiTatCa();
        loadDataToTable(data);
    }
    
    private void loadDataToTable(Vector<Vector<String>> data) {
        Vector<String> columnNames = new Vector<>();
        columnNames.add("Họ tên");
        columnNames.add("Phòng ban");
        columnNames.add("Loại NV");
        columnNames.add("Lương");
        
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tableDanhSach.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDanhSach = new javax.swing.JTable();
        lblTieuDe = new javax.swing.JLabel();
        pnlTimKiem = new javax.swing.JPanel();
        cbNgach = new javax.swing.JComboBox<>();
        txtPhongBan = new javax.swing.JTextField();
        cbLoaiHD = new javax.swing.JComboBox<>();
        btnTinhLuong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTongLuong = new javax.swing.JTextField();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tính lương nhân viên");

        tableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Họ tên", "Phòng ban", "Loại NV", "Lương"
            }
        ));
        jScrollPane1.setViewportView(tableDanhSach);

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTieuDe.setText("Tính lương nhân viên");

        pnlTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        cbNgach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biên chế", "Hợp đồng" }));

        cbLoaiHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NH", "DH" }));

        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemLayout = new javax.swing.GroupLayout(pnlTimKiem);
        pnlTimKiem.setLayout(pnlTimKiemLayout);
        pnlTimKiemLayout.setHorizontalGroup(
            pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbNgach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPhongBan)
                    .addComponent(cbLoaiHD, 0, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnTinhLuong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemLayout.setVerticalGroup(
            pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNgach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhLuong))
                .addGap(18, 18, 18)
                .addComponent(txtPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLoaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tổng lương:");

        txtTongLuong.setEditable(false);
        txtTongLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTongLuong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTieuDe)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDong))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDong))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        double tongLuong = 0;
        Vector<Vector<String>> data = null;
        
        if ("NGACH".equals(cheDoTinhLuong)) {
            String ngach = (String) cbNgach.getSelectedItem();
            tongLuong = QLNhanVien.quanLy.tinhTongLuongTheoNgach(ngach);
            data = QLNhanVien.quanLy.lietKeTheoNgach(ngach);
        } else if ("PHONGBAN".equals(cheDoTinhLuong)) {
            String phongBan = txtPhongBan.getText().trim();
            if (phongBan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập phòng ban!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            tongLuong = QLNhanVien.quanLy.tinhTongLuongTheoPhongBan(phongBan);
            data = QLNhanVien.quanLy.lietKeTheoPhongBan(phongBan);
        } else if ("LOAIHD".equals(cheDoTinhLuong)) {
            String loaiHD = (String) cbLoaiHD.getSelectedItem();
            tongLuong = QLNhanVien.quanLy.tinhTongLuongTheoLoaiHopDong(loaiHD);
            data = QLNhanVien.quanLy.lietKeTheoLoaiHopDong(loaiHD);
        }
        
        txtTongLuong.setText(df.format(tongLuong));
        
        if (data != null) {
            loadDataToTable(data);
            if (data.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có nhân viên nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTinhLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JComboBox<String> cbLoaiHD;
    private javax.swing.JComboBox<String> cbNgach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlTimKiem;
    private javax.swing.JTable tableDanhSach;
    private javax.swing.JTextField txtPhongBan;
    private javax.swing.JTextField txtTongLuong;
    // End of variables declaration//GEN-END:variables
}


