/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai2_2;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
/**
 *
 * @author Đinh Ngọc Năng 2280602045 22DTHG3
 */
public class frmTinhLuong extends javax.swing.JFrame {
    
    private String cheDoTinhLuong = ""; // "NGACH", "PHONGBAN", "LOAIHD"
    private DecimalFormat df = new DecimalFormat("#,###.00");

    /**
     * Creates new form frmTinhLuong
     */
    public frmTinhLuong() {
        initComponents();
    }
    
    public void setCheDoTinhLuong(String cheDo) {
        this.cheDoTinhLuong = cheDo;
        if ("NGACH".equals(cheDo)) {
            lblTieuDe.setText("Tính lương theo ngạch");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(true);
            txtPhongBan.setVisible(false);
            cbLoaiHD.setVisible(false);
        } else if ("PHONGBAN".equals(cheDo)) {
            lblTieuDe.setText("Tính lương theo phòng ban");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(false);
            txtPhongBan.setVisible(true);
            cbLoaiHD.setVisible(false);
        } else if ("LOAIHD".equals(cheDo)) {
            lblTieuDe.setText("Tính lương theo loại hợp đồng");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(false);
            txtPhongBan.setVisible(false);
            cbLoaiHD.setVisible(true);
        }
    }
    
    public void tinhLuongTatCa() {
// 1. Tính toán (Đã chạy ngon)
        double tongLuong = QLNhanVien.quanLy.tinhTongLuong();
        txtTongLuong.setText(df.format(tongLuong));
        
        // 2. Ẩn panel tìm kiếm
        lblTieuDe.setText("Tính lương tất cả nhân viên");
 
        
        // 3. Đổ dữ liệu (Đã có dữ liệu)
        Vector<Vector<String>> data = QLNhanVien.quanLy.hienThiTatCa();
        loadDataToTable(data);
        
        // --- THÊM 2 DÒNG NÀY ĐỂ SỬA LỖI MẤT BẢNG ---
        this.revalidate(); // Tính toán lại bố cục (Layout)
        this.repaint();    // Vẽ lại giao diện ngay lập tức
    }
    
    private void loadDataToTable(Vector<Vector<String>> data) {
        Vector<String> columnNames = new Vector<>();
        columnNames.add("Họ tên");
        columnNames.add("Phòng ban");
        columnNames.add("Loại NV");
        columnNames.add("Lương");
        
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tableDanhSach.setModel(model);
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe = new javax.swing.JLabel();
        pnlTimKiem = new javax.swing.JPanel();
        cbNgach = new javax.swing.JComboBox();
        txtPhongBan = new javax.swing.JTextField();
        cbLoaiHD = new javax.swing.JComboBox();
        btnTinhLuong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTongLuong = new javax.swing.JTextField();
        btnDong = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDanhSach = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tính lương nhân viên");

        lblTieuDe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTieuDe.setText("Tính lương nhân viên");

        pnlTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        cbNgach.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biên chế", "Hợp đồng" }));
        pnlTimKiem.add(cbNgach);

        txtPhongBan.setColumns(5);
        pnlTimKiem.add(txtPhongBan);

        cbLoaiHD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ngắn hạn", "Dài hạn" }));
        pnlTimKiem.add(cbLoaiHD);

        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });
        pnlTimKiem.add(btnTinhLuong);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tổng lương:");

        txtTongLuong.setEditable(false);
        txtTongLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTongLuong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTongLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongLuongActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        tableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDanhSach);

        jLabel2.setText("Đinh Ngọc Năng 2280602045 22DTHG3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnlTimKiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTieuDe)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTongLuong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addGap(88, 88, 88)
                                .addComponent(btnDong)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTieuDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        double tongLuong = 0;
        Vector<Vector<String>> data = null;
        
        if ("NGACH".equals(cheDoTinhLuong)) {
            String ngach = (String) cbNgach.getSelectedItem();
            tongLuong = QLNhanVien.quanLy.tinhTongLuongTheoNgach(ngach);
            data = QLNhanVien.quanLy.lietKeTheoNgach(ngach);
        } else if ("PHONGBAN".equals(cheDoTinhLuong)) {
            String phongBan = txtPhongBan.getText().trim();
            if (phongBan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập phòng ban!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            tongLuong = QLNhanVien.quanLy.tinhTongLuongTheoPhongBan(phongBan);
            data = QLNhanVien.quanLy.lietKeTheoPhongBan(phongBan);
        } else if ("LOAIHD".equals(cheDoTinhLuong)) {
            String loaiHD = (String) cbLoaiHD.getSelectedItem();
            tongLuong = QLNhanVien.quanLy.tinhTongLuongTheoLoaiHopDong(loaiHD);
            data = QLNhanVien.quanLy.lietKeTheoLoaiHopDong(loaiHD);
        }
        
        txtTongLuong.setText(df.format(tongLuong));
        
        if (data != null) {
            loadDataToTable(data);
            if (data.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có nhân viên nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void txtTongLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongLuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTinhLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JComboBox cbLoaiHD;
    private javax.swing.JComboBox cbNgach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlTimKiem;
    private javax.swing.JTable tableDanhSach;
    private javax.swing.JTextField txtPhongBan;
    private javax.swing.JTextField txtTongLuong;
    // End of variables declaration//GEN-END:variables
}


