/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai2_2;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Đinh Ngọc Năng 2280602045 22DTHG3
 */
public class frmTimKiemNhanVien extends javax.swing.JFrame {
    
    private String cheDoLietKe = ""; // "NGACH", "PHONGBAN", "LOAIHD"

    /**
     * Creates new form frmTimKiemNhanVien
     */
    public frmTimKiemNhanVien() {
        initComponents();
        hienThiTatCa();
    }
    
    public void setCheDoLietKe(String cheDo) {
        this.cheDoLietKe = cheDo;
        if ("NGACH".equals(cheDo)) {
            lblTieuDe.setText("Liệt kê theo ngạch");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(true);
            txtPhongBan.setVisible(false);
            cbLoaiHD.setVisible(false);
        } else if ("PHONGBAN".equals(cheDo)) {
            lblTieuDe.setText("Liệt kê theo phòng ban");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(false);
            txtPhongBan.setVisible(true);
            cbLoaiHD.setVisible(false);
        } else if ("LOAIHD".equals(cheDo)) {
            lblTieuDe.setText("Liệt kê theo loại hợp đồng");
            pnlTimKiem.setVisible(true);
            cbNgach.setVisible(false);
            txtPhongBan.setVisible(false);
            cbLoaiHD.setVisible(true);
        }
    }
    
    public void hienThiTatCa() {
        Vector<Vector<String>> data = QLNhanVien.quanLy.hienThiTatCa();
        loadDataToTable(data);
        lblTieuDe.setText("Danh sách tất cả nhân viên");
        pnlTimKiem.setVisible(false);
    }
    
    private void loadDataToTable(Vector<Vector<String>> data) {
        Vector<String> columnNames = new Vector<>();
        columnNames.add("Họ tên");
        columnNames.add("Phòng ban");
        columnNames.add("Loại NV");
        columnNames.add("Lương");
        
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tableDanhSach.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe = new javax.swing.JLabel();
        pnlTimKiem = new javax.swing.JPanel();
        cbNgach = new javax.swing.JComboBox();
        txtPhongBan = new javax.swing.JTextField();
        cbLoaiHD = new javax.swing.JComboBox();
        btnTimKiem = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDanhSach = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liệt kê nhân viên");

        lblTieuDe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTieuDe.setText("Danh sách nhân viên");
        lblTieuDe.setPreferredSize(new java.awt.Dimension(200, 50));

        pnlTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        cbNgach.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biên chế", "Hợp đồng" }));
        pnlTimKiem.add(cbNgach);
        pnlTimKiem.add(txtPhongBan);

        cbLoaiHD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ngắn hạn", "Dài hạn" }));
        pnlTimKiem.add(cbLoaiHD);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        pnlTimKiem.add(btnTimKiem);

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        tableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDanhSach);

        jLabel8.setText("Đinh Ngọc Năng 2280602045 22DTHG3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        Vector<Vector<String>> data = null;
        
        if ("NGACH".equals(cheDoLietKe)) {
            String ngach = (String) cbNgach.getSelectedItem();
            data = QLNhanVien.quanLy.lietKeTheoNgach(ngach);
        } else if ("PHONGBAN".equals(cheDoLietKe)) {
            String phongBan = txtPhongBan.getText().trim();
            if (phongBan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập phòng ban!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            data = QLNhanVien.quanLy.lietKeTheoPhongBan(phongBan);
        } else if ("LOAIHD".equals(cheDoLietKe)) {
            String loaiHD = (String) cbLoaiHD.getSelectedItem();
            data = QLNhanVien.quanLy.lietKeTheoLoaiHopDong(loaiHD);
        }
        
        if (data != null) {
            loadDataToTable(data);
            if (data.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTimKiemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTimKiemNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox cbLoaiHD;
    private javax.swing.JComboBox cbNgach;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlTimKiem;
    private javax.swing.JTable tableDanhSach;
    private javax.swing.JTextField txtPhongBan;
    // End of variables declaration//GEN-END:variables
}


