/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai2_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Đinh Ngọc Năng 2280602045 22DTHG3
 */
public class frmTaoNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form frmTaoNhanVien
     */
    public frmTaoNhanVien() {
        initComponents();
        // Ẩn panel NVHD ban đầu
        pnlNVHD.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtPhongBan = new javax.swing.JTextField();
        rbNVBC = new javax.swing.JRadioButton();
        rbNVHD = new javax.swing.JRadioButton();
        pnlNVBC = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtHeSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoNamCongTac = new javax.swing.JTextField();
        pnlNVHD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtLuongHopDong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbLoaiHopDong = new javax.swing.JComboBox();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        lblTieuDe = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tạo nhân viên");

        jLabel1.setText("Họ tên:");

        jLabel2.setText("Phòng ban:");

        jLabel3.setText("Loại nhân viên:");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        rbNVBC.setSelected(true);
        rbNVBC.setText("Nhân viên biên chế");
        rbNVBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNVBCActionPerformed(evt);
            }
        });

        rbNVHD.setText("Nhân viên hợp đồng");
        rbNVHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNVHDActionPerformed(evt);
            }
        });

        pnlNVBC.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin NVBC"));

        jLabel4.setText("Hệ số lương:");
        pnlNVBC.add(jLabel4);

        txtHeSoLuong.setColumns(10);
        pnlNVBC.add(txtHeSoLuong);

        jLabel5.setText("Số năm công tác:");
        pnlNVBC.add(jLabel5);

        txtSoNamCongTac.setColumns(10);
        pnlNVBC.add(txtSoNamCongTac);

        pnlNVHD.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin NVHD"));

        jLabel6.setText("Lương hợp đồng:");
        pnlNVHD.add(jLabel6);

        txtLuongHopDong.setColumns(10);
        txtLuongHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongHopDongActionPerformed(evt);
            }
        });
        pnlNVHD.add(txtLuongHopDong);

        jLabel7.setText("Loại hợp đồng:");
        pnlNVHD.add(jLabel7);

        cbLoaiHopDong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ngắn hạn", "Dài hạn" }));
        pnlNVHD.add(cbLoaiHopDong);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        lblTieuDe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTieuDe.setText("Tạo nhân viên");

        jLabel8.setText("Đinh Ngọc Năng 2280602045 22DTHG3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rbNVBC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbNVHD)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(txtHoTen))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDong))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNVBC, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addComponent(pnlNVHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTieuDe)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTieuDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbNVBC)
                    .addComponent(rbNVHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNVBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNVHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuu)
                            .addComponent(btnDong))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNVBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNVBCActionPerformed
        pnlNVBC.setVisible(true);
        pnlNVHD.setVisible(false);
    }//GEN-LAST:event_rbNVBCActionPerformed

    private void rbNVHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNVHDActionPerformed
        pnlNVBC.setVisible(false);
        pnlNVHD.setVisible(true);
    }//GEN-LAST:event_rbNVHDActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            String hoTen = txtHoTen.getText().trim();
            String phongBan = txtPhongBan.getText().trim();
            
            if (hoTen.isEmpty() || phongBan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            NhanVien nv = null;
            
            if (rbNVBC.isSelected()) {
                // Tạo NVBC
                String heSoStr = txtHeSoLuong.getText().trim();
                String soNamStr = txtSoNamCongTac.getText().trim();
                
                if (heSoStr.isEmpty() || soNamStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin NVBC!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                double heSoLuong = Double.parseDouble(heSoStr);
                int soNamCongTac = Integer.parseInt(soNamStr);
                
                if (heSoLuong <= 0 || soNamCongTac < 0) {
                    JOptionPane.showMessageDialog(this, "Hệ số lương phải > 0 và số năm công tác >= 0!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                nv = new NVBC(hoTen, phongBan, heSoLuong, soNamCongTac);
            } else {
                // Tạo NVHD
                String luongStr = txtLuongHopDong.getText().trim();
                
                if (luongStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập lương hợp đồng!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                double luongHopDong = Double.parseDouble(luongStr);
                String loaiHD = (String) cbLoaiHopDong.getSelectedItem();
                
                if (luongHopDong <= 0) {
                    JOptionPane.showMessageDialog(this, "Lương hợp đồng phải > 0!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                nv = new NVHD(hoTen, phongBan, luongHopDong, loaiHD);
            }
            
            // Thêm vào danh sách
            QLNhanVien.quanLy.themNhanVien(nv);
            
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            
            // Xóa form
            txtHoTen.setText("");
            txtPhongBan.setText("");
            txtHeSoLuong.setText("");
            txtSoNamCongTac.setText("");
            txtLuongHopDong.setText("");
            cbLoaiHopDong.setSelectedIndex(0);
            rbNVBC.setSelected(true);
            pnlNVBC.setVisible(true);
            pnlNVHD.setVisible(false);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu số không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtLuongHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongHopDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongHopDongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTaoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTaoNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox cbLoaiHopDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlNVBC;
    private javax.swing.JPanel pnlNVHD;
    private javax.swing.JRadioButton rbNVBC;
    private javax.swing.JRadioButton rbNVHD;
    private javax.swing.JTextField txtHeSoLuong;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuongHopDong;
    private javax.swing.JTextField txtPhongBan;
    private javax.swing.JTextField txtSoNamCongTac;
    // End of variables declaration//GEN-END:variables
}


