/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai_02;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * @author Đinh Ngọc Năng 2280602045 22DTHG3
 */
public class VietFile extends javax.swing.JFrame {

    /**
     * Creates new form VietFile
     */
    public VietFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        txtNhapChuoi = new javax.swing.JTextField();
        btnReadFileNhiPhan = new javax.swing.JButton();
        btnReadFileVanBan = new javax.swing.JButton();
        btnWriteFileNhiPhan = new javax.swing.JButton();
        btnWriteFileVanBan = new javax.swing.JButton();
        txtHienThiKetQua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập tên tệp tin");

        jLabel2.setText("Nhập chuỗi");

        jLabel3.setText("Nội dung file");

        btnReadFileNhiPhan.setText("Đọc File nhị phân");
        btnReadFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadFileNhiPhanActionPerformed(evt);
            }
        });

        btnReadFileVanBan.setText("Đọc File văn bản");
        btnReadFileVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadFileVanBanActionPerformed(evt);
            }
        });

        btnWriteFileNhiPhan.setText("Ghi File nhị phân");
        btnWriteFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteFileNhiPhanActionPerformed(evt);
            }
        });

        btnWriteFileVanBan.setText("Ghi File văn bản");
        btnWriteFileVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteFileVanBanActionPerformed(evt);
            }
        });

        txtHienThiKetQua.setBackground(new java.awt.Color(153, 204, 255));

        jLabel4.setText("Đinh Ngọc Năng 2280602045 22DTHG3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFileName)
                            .addComponent(txtNhapChuoi)
                            .addComponent(txtHienThiKetQua)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReadFileVanBan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnWriteFileVanBan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReadFileNhiPhan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnWriteFileNhiPhan)))))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNhapChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHienThiKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReadFileNhiPhan)
                    .addComponent(btnWriteFileNhiPhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReadFileVanBan)
                    .addComponent(btnWriteFileVanBan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWriteFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteFileNhiPhanActionPerformed
// 1. Khởi tạo mảng byte để lưu ký tự. Kích thước 20 là kích thước cố định, cần kiểm tra lại
    byte b[] = new byte[20]; 
    File file;
    int i;
    
    // 2. Chuyển nội dung từ txtNhapChuoi sang mảng ký tự và sau đó sang mảng byte b[]
    char s[] = txtNhapChuoi.getText().toCharArray(); 
    for (i = 0; i < s.length; i++) {
        b[i] = (byte) s[i];
    }
    
    // 3. Xử lý ghi file
    try {
        // Tạo đối tượng File từ tên file nhập vào
        file = new File(txtFileName.getText());
        
        // Tạo luồng ghi file nhị phân
        FileOutputStream fo = new FileOutputStream(file); 
        
        // Ghi mảng byte b[] vào file (ghi 20 bytes cố định, bao gồm cả những byte trống)
        fo.write(b); 
        
        // Đóng luồng
        fo.close(); 
        
    } catch(IOException e) { 
        e.printStackTrace(); 
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWriteFileNhiPhanActionPerformed

    private void btnReadFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadFileNhiPhanActionPerformed
byte b[] = new byte[20]; 
    File file;
    
    try {
        file = new File(txtFileName.getText());
        FileInputStream fi = new FileInputStream(file);
        
        // Kiểm tra xem file có sẵn dữ liệu để đọc không
        if (fi.available() > 0) {
            // Đọc dữ liệu vào mảng b
            fi.read(b); 
        }
        fi.close();
        
        // Đọc và hiển thị nội dung
        String s = new String(b);
        txtHienThiKetQua.setText(s.trim()); // trim() để loại bỏ ký tự trắng thừa nếu mảng b lớn hơn dữ liệu
        
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, e.toString());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReadFileNhiPhanActionPerformed

    private void btnWriteFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteFileVanBanActionPerformed
try {
        // Tạo đối tượng FileWriter. true sẽ ghi nối tiếp, nếu không có là ghi đè.
        FileWriter fw = new FileWriter(new File(txtFileName.getText())); 
        
        // Ghi nội dung từ ô nhập chuỗi vào file
        fw.write(txtNhapChuoi.getText()); 
        
        fw.close();
        
    } catch(Exception e) {
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWriteFileVanBanActionPerformed

    private void btnReadFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadFileVanBanActionPerformed
try {
        // Khởi tạo FileReader để đọc file
        FileReader fr = new FileReader(new File(txtFileName.getText()));
        
        // Khởi tạo BufferedReader để đọc hiệu quả hơn
        BufferedReader br = new BufferedReader(fr);
        
        // Khởi tạo StringBuffer để xây dựng chuỗi kết quả
        StringBuffer sb = new StringBuffer(); 
        
        // Mảng char để đọc từng khối dữ liệu (đọc tối đa 512 ký tự mỗi lần)
        char ca[] = new char[512]; 
        int i;
        
        // Lặp cho đến khi không còn dữ liệu để đọc (br.read trả về -1)
        while ((i = br.read(ca)) != -1) { 
            // Thêm dữ liệu đã đọc vào StringBuffer
            sb.append(String.valueOf(ca, 0, i)); 
        }
        
        br.close();
        fr.close();
        
        // Hiển thị kết quả đọc được vào ô hiển thị kết quả
        txtHienThiKetQua.setText(sb.toString()); 
        
    } catch(Exception e) {
        e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReadFileVanBanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VietFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VietFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VietFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VietFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VietFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadFileNhiPhan;
    private javax.swing.JButton btnReadFileVanBan;
    private javax.swing.JButton btnWriteFileNhiPhan;
    private javax.swing.JButton btnWriteFileVanBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtHienThiKetQua;
    private javax.swing.JTextField txtNhapChuoi;
    // End of variables declaration//GEN-END:variables
}
