/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai2_1; // 

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonGroup;

/**
 *
 * @author Đinh Ngọc Năng 2280602045 22DTHG3
 */
public class frmTimKiemUser extends javax.swing.JFrame {
// --- 1. HÀM HIỂN THỊ BẢNG (Được đặt đúng trong Class) ---
    private void hienThiBang(String sql) {
        try {
            // Định nghĩa tên cột
            String[] columnNames = {"Username", "Password", "Đường dẫn", "Quyền"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            // Kết nối CSDL
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.Query(sql);

            // Kiểm tra nếu kết nối lỗi (rs bị null)
            if (rs == null) {
                JOptionPane.showMessageDialog(null, "Lỗi: Không thể lấy dữ liệu từ Database (ResultSet null).");
                return;
            }

            // Đọc dữ liệu
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("username"));
                row.add(rs.getString("password"));
                row.add(rs.getString("path"));
                
                int per = rs.getInt("per");
                if (per == 0) row.add("Read");
                else if (per == 1) row.add("Write");
                else row.add("Full");

                model.addRow(row);
            }
            
            // Đổ dữ liệu vào bảng
            tableKetQua.setModel(model);
            
        } catch (Exception e) {
            e.printStackTrace(); // In lỗi ra console để dễ sửa
            JOptionPane.showMessageDialog(null, "Lỗi hiển thị bảng: " + e.toString());
        }
    }
// --- 2. HÀM KHỞI TẠO (CONSTRUCTOR) ---
    public frmTimKiemUser() {
        initComponents(); // Khởi tạo giao diện (do NetBeans sinh ra)
        
        // Nhóm các nút tròn lại
        ButtonGroup bg = new ButtonGroup();
        bg.add(cbRead);
        bg.add(cbWrite);
        bg.add(cbFull);
        cbRead.setSelected(true); // Mặc định chọn Read

        // Hiển thị tất cả dữ liệu ngay khi mở form
        hienThiBang("SELECT * FROM taikhoan");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbRead = new javax.swing.JRadioButton();
        cbWrite = new javax.swing.JRadioButton();
        cbFull = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKetQua = new javax.swing.JTable();
        btnTimKiemTen = new javax.swing.JButton();
        btnTimKiemQuyen = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ten User:");

        jLabel2.setText("Quyen:");

        cbRead.setText("Read");

        cbWrite.setText("Write");

        cbFull.setText("Full");

        tableKetQua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ten User", "Mau khau", "Duong dan", "Quyen"
            }
        ));
        jScrollPane2.setViewportView(tableKetQua);

        btnTimKiemTen.setText("Tim theo ten");
        btnTimKiemTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTenActionPerformed(evt);
            }
        });

        btnTimKiemQuyen.setText("Tim theo quyen");
        btnTimKiemQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemQuyenActionPerformed(evt);
            }
        });

        jButton3.setText("Huy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Đinh Ngọc Năng 2280602045 22DTHG3");

        jLabel6.setText("Đinh Ngọc Năng 2280602045 22DTHG3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimKiem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbRead)
                                .addGap(18, 18, 18)
                                .addComponent(cbWrite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbFull, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemQuyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiemQuyen)
                    .addComponent(jLabel2)
                    .addComponent(cbRead)
                    .addComponent(cbWrite)
                    .addComponent(cbFull))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel6))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(jLabel5)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTenActionPerformed
String ten = txtTimKiem.getText().trim();
        if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên!");
            return;
        }
        // Tìm gần đúng bằng SQL
        String sql = "SELECT * FROM taikhoan WHERE username LIKE '%" + ten + "%'";
        hienThiBang(sql);
    }//GEN-LAST:event_btnTimKiemTenActionPerformed

    private void btnTimKiemQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemQuyenActionPerformed
int quyen = 0;
        if (cbRead.isSelected()) quyen = 0;
        else if (cbWrite.isSelected()) quyen = 1;
        else quyen = 2;

        // Tìm chính xác quyền bằng SQL
        String sql = "SELECT * FROM taikhoan WHERE per = " + quyen;
        hienThiBang(sql);
    }//GEN-LAST:event_btnTimKiemQuyenActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmTimKiemUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiemQuyen;
    private javax.swing.JButton btnTimKiemTen;
    private javax.swing.JRadioButton cbFull;
    private javax.swing.JRadioButton cbRead;
    private javax.swing.JRadioButton cbWrite;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableKetQua;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
