#Threshold NIDS config
#Thu Dec 25 12:18:21 GMT+07:00 2025
adaptiveEnabled=false
adaptiveFactor=3
blockBaseMs=30000
maxBlockMs=600000
port=9090
refreshMs=1000
staticThreshold=20
windowMs=10000

# NEW - Log Collector (UDP)
collectorEnabled=true
collectorPort=5514
maxEvents=2000